#
# Copyright (c) 2015 by Delphix. All rights reserved.
#

---

- name: npmjs-proxy | Create {{ npmjs_server_dir }}
  file:
    path="{{ npmjs_server_dir }}"
    state=directory

- name: npmjs-proxy | Run the Docker container for the npmjs proxy
  docker:
    image=rnbwd/sinopia
    name=sinopia
    ports="{{ npmjs_server_port }}:4873"
    volumes="{{ npmjs_server_dir }}:/sinopia/storage"
